plugins:
  - jekyll-remote-theme
title: Suchita Kulkarni
logo: /assets/img/kulkarni_photo.jpg 
description: Photo of Dr. Kulkarni
linkedin_username: suchitakulkarni
show_downloads: false
theme: jekyll-theme-minimal
