plugins:
  - jekyll-remote-theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Suchita Kulkarni, PhD
logo: /assets/img/kulkarni_photo.jpg 
description: Photo of Dr. Kulkarni
platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/suchitakulkarni
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/suchitakulkarni
show_downloads: false
navigation:
  - name: Homepage
    link: ./index.html
  - name: Taylor Swift music analysis
    link: ./projects/Taylor_Swift_dataanalysis.html
  - name: Taylor Swift music analysis (content recommendation system)
    link: ./projects/T_Swift_Finale.html
  - name: PCOS analysis
    link: ./projects/PCOS.html
  - name: Anomaly detection app
    link: https://pinnlearning.streamlit.app/
    
    

